config/routes.rb
SampleApp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  root 'static_pages#home'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete' 

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<h1 style="position:relative; bottom:50px">About</h1>
<p style ="position:relative; bottom:60px">
      88% of businesses that have loyalty programs are more profitable than competitors who do not. Yet, only 30% of current restaurant operators offer loyalty or frequent-diner programs. FoodFeed is a new solution is to solicit customer loyalty in the most convenient way possible for both customers and restaurants: SMS.
</p>
<p>
	Please keep an eye out for launch in Spring 2014.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1 style="position:relative;bottom:50px">Contact</h1>
<p style="position:relative;bottom:60px">
  Please 

<a href="mailto:schmatt@wharton.upenn.edu" target="_top">
email me</a>
  for more information.
</p>

app/views/static_pages/help.html.erb
<h1>Help</h1>
<p>
    Write some stuff here.
</p>
  

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/stats' %>
      </section>
      <section>
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="span8">
      <h3>News Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>

<% else %>  
  <div class="row" style="background:#e2f1ff; position:relative; bottom:60px; height:380px">    
    <div style="position:relative; right:190px; top:90px">
      <h1 style="position:relative; top:6px">New User? Sign Up</h1>
      <h2 style="color:green; font-size:200%">It's free</h2>
    </div>
    <div class="span6 offset3" style="text-align:center; color:white; margin-top:5px; position:relative; right:10px; bottom:10px">
      <%= form_for(:session, url: sessions_path) do |f| %>
        <div style="position:relative; bottom:12px; left:120px">
          <div style="position:relative; bottom:186.2px; left:27px; width:220px">
            <%= f.label :email %>
            <%= f.text_field :email %>
          </div>

          <div style="position:relative; bottom:251px; left:260px; width:220px">
            <%= f.label :password %>
            <%= f.password_field :password %>
          </div>


          <div style="margin-top:7px; position:relative; bottom:311px; left:490px; width:100px">
            <%= f.submit "Sign in", class: "btn btn-large btn-primary" %>
          </div>
        </div>
      <% end %>

      <div style="color:black;  position:relative; bottom:310px; left:260px">
        <%= form_for(:user, url: users_path) do |f| %>
          <%= f.label :name %>
          <%= f.text_field :name %>

          <%= f.label :email %>
          <%= f.text_field :email %>

          <%= f.label :password %>
          <%= f.password_field :password %>

          <%= f.label :password_confirmation, "Confirmation" %>
          <%= f.password_field :password_confirmation %>

          <div style="position:relative; top:10px; left:0px"><%= f.submit "Create my account", class: "btn btn-large btn-success" %></div>
        <% end %>

      </div>



    </div>
  </div>
  
<% end %>